### ISSUE TITLE
Apache not starting

### ISSUE THREAD

**Issue by vikbez** [scaleway-community/scaleway-owncloud#11]
Started image does not have apache2 running;
when ssh-ing and trying to start apache2:

```
root@to-rm:/var/www/owncloud# service apache2 start
 * Starting web server apache2                                                                                                                                                                          *
 * The apache2 configtest failed.
Output of config test was:
AH00526: Syntax error on line 32 of /etc/apache2/sites-enabled/default-ssl.conf:
SSLCertificateFile: file '/etc/ssl/certs/ssl-cert-snakeoil.pem' does not exist or is empty
Action 'configtest' failed.
The Apache error log may have more information.
```

**Comment by moul** [comment]
@QuentinPerez @edouardb, any idea ?

**Comment by kpmy** [comment]
You forgot to pre-install ssl-cert package, so apache didn't found default cert. 
After installing apache runs normally.

**Comment by moul** [comment]
Ok so maybe this commit fixed the issue: https://github.com/scaleway-community/scaleway-owncloud/commit/ce68e8c5529a64b72e976e1ca8f64caf25b3d080

We only need to rebuild the image though

**Comment by moul** [comment]
It seems fixed in the latest version

Do not hesitate to reopen this issue if you encounter this problem again
