### ISSUE TITLE
Publish a new version on docker hub

### ISSUE THREAD

**Issue by Spy-Seth** [scaleway-community/scaleway-owncloud#12]
The image on the hub repository is not up to date with the repo. The `ssl-cert` patch is not present. Could publish a more recent version?

**Comment by moul** [comment]
Hi @Spy-Seth, thanks for your feedback, we will release a new image very soon and we are working on a system which alerts us when an image is outdated

**Comment by moul** [comment]
Depends on https://github.com/scaleway/qa/issues/116

**Comment by moul** [comment]
The latest version is now public: http://devhub.scaleway.com/#/images/owncloud:latest

**Comment by Spy-Seth** [comment]
:+1:
