### ISSUE TITLE
Missing Something.

### ISSUE THREAD

**Issue by jessekrembs** [scaleway-community/scaleway-owncloud#13]
Has something changed or missing from this deployment? I'm getting a 404 in the /owncloud from the Imagehub instance.

**Comment by moul** [comment]
Hi @jessekrembs, thank you for reporting this issue,

This is fixed in #14 and will be available in the next release of this image
For now you can hot-patch your running server by running this command:

```console
$ ln -s /var/www/owncloud /var/www/html/owncloud
```
