### ISSUE TITLE
MySQL PASSWORD FAILED AFTER INSTALLATION !

### ISSUE THREAD

**Issue by channawegg** [scaleway-community/scaleway-owncloud#28]
Hi Everyone,

The finalization of the installation of Owncloud is compromised because the password provided in the .my.cnf file does not work and returns an error.

Erreur
Nom d'utilisateur et/ou mot de passe MySQL/MariaDB non valide 
Vous devez spécifier le nom d'un compte existant, ou celui de l'administrateur.

The Scaleway support asked me to send you a message here for that. 
I really need to finish the installation by today, can you please help me. 

Best regards,
C.

**Comment by tbillon** [comment]
I just tried on a C1 and it worked fine. On what kind of instance did you install it ?

**Comment by channawegg** [comment]
In a C2L in Amsterdam.

I can assure you that it doesn't work.

--
*Channa PERERA* / CEO

[image: WEGG] <http://www.wegg.fr>

WEGG
13 rue Voltaire 92300 Levallois-Perret France
Tel : +33 1 57 67 77 65 / Fax : +33 9 57 98 52 52 / Skype : channa.p



2017-08-21 17:13 GMT+02:00 Thibault Billon <notifications@github.com>:

**Comment by tbillon** [comment]
Ok I tried again with a C2L in Paris & Amsterdam. Both worked fine. You probably experienced a glitch. Can you delete your server and start again from the beginning ?

**Comment by channawegg** [comment]
Ok I will do that for the 3rd time.

Btw can you please confirm me the process :
As soon as the server is create, I just need to finalise the installation
with the web link without creating the database before ?

Am I right ?

Best regards,

--
*Channa PERERA* / CEO

[image: WEGG] <http://www.wegg.fr>

WEGG
13 rue Voltaire 92300 Levallois-Perret France
Tel : +33 1 57 67 77 65 / Fax : +33 9 57 98 52 52 / Skype : channa.p



2017-08-21 17:30 GMT+02:00 Thibault Billon <notifications@github.com>:

**Comment by tbillon** [comment]
I did it with the scaleway-cli:
```
$ scw --region=ams1 create --commercial-type=C2L ownCloud
a740fc34-f660-4159-bfb0-1d0893aad0ee
$ scw --region=ams1 start a740fc34-f660-4159-bfb0-1d0893aad0ee
$ scw --region=ams1 attach a740fc34-f660-4159-bfb0-1d0893aad0ee
```
Then I opened the server IP address in a browser and that was it.

**Comment by channawegg** [comment]
I did it through the web interface.
It has to work as well. No ?

--
*Channa PERERA* / CEO

[image: WEGG] <http://www.wegg.fr>

WEGG
13 rue Voltaire 92300 Levallois-Perret France
Tel : +33 1 57 67 77 65 / Fax : +33 9 57 98 52 52 / Skype : channa.p



2017-08-21 17:47 GMT+02:00 Thibault Billon <notifications@github.com>:

**Comment by channawegg** [comment]
​It's still the same thing.

Where is what I have done :

I created the server,
Wait 1 day before login to it,
Finalise the installation as written in your howto (when we log on the
public IP of the server)​,
I even tried to do on PostgreSQL.

But it doesn't work !

I even have that message now :

"Une erreur s’est produite pendant la récupération du numéro de version de
PostgreSQL

Veuillez vérifier que vous utilisez PostgreSQL >= 9 , ou regardez dans le
journal d’erreur pour plus d’informations sur ce problème"


Is your image corrupted ?


Please advice.



Regards,



--
*Channa PERERA* / CEO

[image: WEGG] <http://www.wegg.fr>

WEGG
13 rue Voltaire 92300 Levallois-Perret France
Tel : +33 1 57 67 77 65 / Fax : +33 9 57 98 52 52 / Skype : channa.p



2017-08-21 17:53 GMT+02:00 Channa PERERA | Wegg <channa@wegg.fr>:

**Comment by tbillon** [comment]
Ok I think I get it. You try to enter the password from the `.my.cnf` file on the login page ? You don't have to do that any more. Just enter the login/password you want to use and that's it.

**Comment by channawegg** [comment]
If is that the issue, really it's not nice ! I just followed you
instructions.
Please update your images and the instructions you give to the clients
trough them.

I hope I won't be charged for Scaleway's mistake, actually for server that
I never use.

Regards,


--
*Channa PERERA* / CEO

[image: WEGG] <http://www.wegg.fr>

WEGG
13 rue Voltaire 92300 Levallois-Perret France
Tel : +33 1 57 67 77 65 / Fax : +33 9 57 98 52 52 / Skype : channa.p



2017-08-24 10:27 GMT+02:00 Thibault Billon <notifications@github.com>:
