### ISSUE TITLE
Release please!

### ISSUE THREAD

**Issue by sils1297** [scaleway-community/scaleway-owncloud#8]
I see you have added https support which is a killer feature, plus ownCloud 8.2 is available. Would be nice to have a release.

**Comment by moul** [comment]
Here it is: http://cloud.scaleway.com/#/servers/new?image=e85f79bb-2c48-4b58-b6bc-e38022a9294a

And here the build detail: https://travis-ci.org/scaleway/qa/builds/85714315

Have a nice week-end
